### ISSUE TITLE
Update Travis

### ISSUE THREAD

**Issue by BrandonRomano** [carrot/carrot-api-node#3]
Getting:

> This job is running on our new platform for Legacy Precise builds. Please read our blog post for more information.

We should probably update our Travis setup for this project

**Comment by BrandonRomano** [comment]
Oh wait, this doesn't look like something we should need to fix.  Although we were targeting a super old version of node, so I will update that.

**Comment by hhsnopek** [comment]
any reason for not using https://github.com/request/request?

**Comment by BrandonRomano** [comment]
@kylemac suggested axios -- I've never used request, but so far I am liking the interface axios provides.

I suspect it is because axios uses promises?  And it looks like request uses callbacks?

@kylemac maybe you can speak to this a little better than I can

**Comment by kylemac** [comment]
yeah, thats correct – I wanted to try axios out bc it uses promises.

**Comment by BrandonRomano** [comment]
Also too, this issue was resolved in #2, as I updated travis to use node 4.1 (which I think is the highest you can go with travis ref https://docs.travis-ci.com/user/languages/javascript-with-nodejs)
